# Config file for automatic testing at travis-ci.org
# This file will be regenerated if you run travis_pypi_setup.py

language: python
dist: bionic
python:
  - "3.6"

# workaround to make boto work on travis
# from https://github.com/travis-ci/travis-ci/issues/7940
before_install:
  - sudo rm -f /etc/boto.cfg

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install -U numpy
  - pip install -q -r requirements.txt
  - pip install -q .[full]
  - pip install coveralls

os:
  - linux

# command to run tests, e.g. python setup.py test
script:
  coverage run --source=pythainlp setup.py test

after_success:
  coveralls

# After you create the Github repo and add it to Travis, run the
# travis_pypi_setup.py script to finish PyPI deployment setup
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: wannaphong
  password: cat
  on:
    tags: true
    repo: pythainlp/pythainlp
    #condition: $TOXENV == py35
