build: off

environment:
  matrix:
    - PYTHON: "C:/Python36-x64"
      PYTHON_VERSION: "3.6"
      PYTHON_ARCH: "64"
      ARTAGGER_PKG: "https://github.com/wannaphongcom/artagger/tarball/master#egg=artagger"

init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"  
  - ps: "ls C:/Python*"

install:
  - "chcp 65001"
  - "set PYTHONIOENCODING=utf-8"
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "python --version"
  # - "set ICU_VERSION=62"
  - "pip install --upgrade pip"
  - "pip install coveralls[yaml]"
  - "pip install coverage"
  - "pip install https://www.dropbox.com/s/g84479l8yhv5ohi/PyICU-2.2-cp36-cp36m-win_amd64.whl?dl=1"
  - "pip install %ARTAGGER_PKG%"
  - "pip install -e .[artagger,icu,ipa,ner,thai2fit,deepcut]"

test_script:
  - "pip --version"
  - "coverage run --source=pythainlp setup.py test"

on_success:
  - "coveralls"